name: 테스트 및 커버리지 측정

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction
    
    - name: 테스트 및 커버리지 측정
      run: |
        pytest --cov=. --cov-config=.coveragerc --cov-report=xml --cov-report=term-missing:skip-covered
    
    - name: Codecov에 업로드
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/coverage.xml
        fail_ci_if_error: false
    
    - name: 테스트 결과 보관
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-coverage-report
        path: |
          coverage/html/
          coverage/coverage.xml
          .coverage 